//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolum
    {
        public Bolum()
        {
            this.Ogrenciler = new HashSet<Ogrenciler>();
        }
    
        public int id { get; set; }
        public string bolumAd { get; set; }
        public int fakulteId { get; set; }
    
        public virtual Fakulte Fakulte { get; set; }
        public virtual ICollection<Ogrenciler> Ogrenciler { get; set; }
    }
}
