//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odunc
    {
        public int id { get; set; }
        public int ogrenciId { get; set; }
        public int kitapId { get; set; }
        public System.DateTime oduncTarih { get; set; }
        public System.DateTime teslimTarih { get; set; }
        public bool oduncDurum { get; set; }

        public virtual Kitaplar Kitaplar
        {
            get;
            set;
        }
        public virtual Ogrenciler Ogrenciler
        {
            get;
            set;
        }
    }
}
